#!/bin/sh
#

case "$1" in
  start)
	#/etc/modules-load.myir/myd-jls1028-updatesy.sh
	/usr/bin/start.sh
	#sleep 6
	#/usr/bin/mes & 
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
